### PR TITLE
Need support for secret-less usage #1

### PR DESCRIPTION
**Pull request by RomanSaveljev**
Current implementation is rather limiting as there are more options
to how the bucket access can be configured (IAM role, credentials file
as a bound volume, environment variables through container's environment
file). Enforcing the only way and enforcing keeping .drone.sec is not
really necessary, IMO.

If credentials are insufficient, then the uploading will fail anyway. To
avoid uploads from forks/branches, I think, a more obvious solution should
be present.

### CODE REVIEW

**Comment by RomanSaveljev** [comment]
I could build it, but I was unable to test, because the drone keeps pulling the image.. 
Could you suggest me how to test it so it does not pull from the registry every time?

**Comment by bradrydzewski** [comment]
great, thanks!

**Comment by thyming** [comment]
I don't think this allows passwordless authentication via IAM. 
If the secret and id are not supplied, it breaks out here:
https://github.com/RomanSaveljev/drone-s3/blob/103bf47eba8ad4a00d1a0f2e96dc6b4badccd379/main.go#L65

**Comment by RomanSaveljev** [comment]
@thyming You are correct. The patch needs more patching.

**Pull request merged**
