### PR TITLE
Simple support for different endpoints

### PR DESCRIPTION
**Pull request by csachs**
Hello,

like @alexex I'm interested in using different S3-compatible object storage engines.

I've quickly hacked together this little PR, it adds support for a `endpoint` property stating the desired endpoint URL. If it is omitted, no endpoint is passed to `awscli` and it functions like before.
I've added a `default.s3.signature_version` setting, as the S3 server I've used (minio) only supports v4 signatures, and according to Amazon documentation, all their regions support v4.
So far i've only tested `minio` as object storage engine.

Regards,
Christian

### CODE REVIEW

**Comment by tboerger** [comment]
LGTM

**Comment by bradrydzewski** [comment]
@csachs can you add the new `endpoint` parameter to the `DOCS.md` file?

**Comment by csachs** [comment]
Hi, added it to the DOCS.md … didn't add it to the example below, as I guess that custom endpoints are a rather niche application, and would probably puzzle the vast majority of users.

**Comment by tboerger** [comment]
Still LGTM

**Comment by tboerger** [comment]
> This branch is out-of-date with the base branch

**Comment by bradrydzewski** [comment]
handled by https://github.com/drone-plugins/drone-s3/pull/18 switching to native Go code

**Pull request closed without merging**
